seed_everything: 42
model:
  # hparams mcmc
  mcmc_steps_tr: 20
  mcmc_learning_rate_tr: 1.0
  mcmc_steps_gen: 1024
  mcmc_learning_rate_gen: 1.0
  # hparams optimizer
  optimizer_type: adam
  alpha_penalty: 0
  alpha_cd: 0
  alpha_ce: 1
  lr: 0.001
  beta1: 0.0
  sampler:
    class_path: samplers.MolSampler
    init_args:
      max_len_buffer: 10000
  nn_model:
    class_path: nn_models.dgn.DenseGCN
    init_args:
      in_channels: 4
      num_edge_types: 4
      hidden_channels_list: [64, 64, 64]
      out_channels: 3
data:
  class_path: data_modules.QM9DataModule
  init_args:
    data_dir: '/data/castellana/ebm-molecules/datasets/QM9'
    batch_size: 128
    num_workers: 10

trainer:
  accelerator: gpu
  devices: [3]
  max_epochs: 100
  gradient_clip_val: 0.1
  callbacks:
    - class_path: callbacks.BufferSamplerCallback
    - class_path: callbacks.GenerateCallback
    # - class_path: callbacks.PlotBatchCallback
    - class_path: callbacks.ComputeMolMetricsCallback
      init_args:
        mol_to_generate: 10000

  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: .
      name: QM9_logs
