seed_everything: 42
model:
  # hparams mcmc
  mcmc_steps_tr: 20
  mcmc_learning_rate_tr: 0.1
  mcmc_steps_gen: 64
  mcmc_learning_rate_gen: 0.1
  # hparams optimizer
  optimizer_type: adam
  alpha_penalty: 0.1
  alpha_cd: 1
  alpha_ce: 2
  lr: 0.01
  beta1: 0.0
#  gamma: 0.99
  sampler:
    class_path: samplers.MolSampler
    init_args:
      max_len_buffer: 10000
  nn_model:
    class_path: nn_models.dgn.DenseGCN
    init_args:
      in_channels: 4
      num_edge_types: 4
      hidden_channels_list: [64, 64, 64]
      out_channels: 3
data:
  class_path: data_modules.QM9DataModule
  init_args:
    data_dir: './datasets'
    batch_size: 128
    num_workers: 10

trainer:
  accelerator: auto
  devices: auto
  max_epochs: 61
  gradient_clip_val: 0.1
  callbacks:
    - class_path: callbacks.BufferSamplerCallback
    - class_path: callbacks.GenerateCallback
    # - class_path: callbacks.PlotBatchCallback
    - class_path: callbacks.ComputeMolMetricsCallback
      init_args:
        mol_to_generate: 1000
    - class_path: callbacks.SelfAccuracyCallback
    - class_path: callbacks.ChangeClassCallback
      init_args:
        n_plot_during_generation: 10
        samples_to_plot: 5
        mcmc_steps: 128

  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: logs
      name: QM9/train
