seed_everything: 42
model:
  # hparams mcmc
  mcmc_steps_tr: 20
  mcmc_learning_rate_tr: 1.0
  mcmc_steps_gen: 1024
  mcmc_learning_rate_gen: 1.0
  # hparams optimizer
  alpha_penalty: 0.1
  alpha_ce: 1
  lr: 0.001
  beta1: 0.0
  sampler:
    class_path: samplers.GraphSBMSampler
    init_args:
      max_len_buffer: 10000
  nn_model:
    class_path: nn_models.dgn.DenseGCN
    init_args:
      in_channels: 1
      hidden_channels_list: [10]
      out_channels: 2
data:
  class_path: data_modules.SBMDataModule
  init_args:
    data_dir: './datasets'
    name: easy
    batch_size: 128
    num_workers: 0

trainer:
  accelerator: auto
  devices: auto
  max_epochs: 61
  gradient_clip_val: 0 #0.1
  callbacks:
    - class_path: callbacks.BufferSamplerCallback
    - class_path: callbacks.GenerateCallback
    - class_path: callbacks.SelfAccuracyCallback
#    - class_path: callbacks.ChangeClassCallback
#      init_args:
#        samples_to_plot: 2
#        mcmc_steps_multiplier: 1
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: logs
      name: SBM/train
