seed_everything: 42
model:
  # hparams mcmc
  mcmc_steps_tr: 40
  mcmc_learning_rate_tr: 1.0
  mcmc_steps_gen: 1024
  mcmc_learning_rate_gen: 1.0
  # hparams loss
  alpha_penalty: 0.1
  alpha_ce: 1
  alpha_cd: 1
  # hparams optimizer
  optimizer_type: sgd
  lr: 0.1
  beta1: 0.0
  lr_step_size: 10
  gamma: 0.99
  sampler:
    class_path: samplers.GraphSampler
    init_args:
      max_len_buffer: 8000
      max_num_nodes: 30
  nn_model:
    class_path: nn_models.gcn.GCN_Dense
    init_args:
      in_channels: 1
      hidden_channels_list: [10]
      out_channels: 2
data:
  class_path: data_modules.SBMDataModule
  init_args:
    name: easy
    batch_size: 256
    num_workers: 5

trainer:
  accelerator: auto
  devices: auto
  max_epochs: 26
  gradient_clip_val: 0
  log_every_n_steps: 10
  callbacks:
    - class_path: utils.callbacks.BufferSamplerCallback
    - class_path: utils.callbacks.GenerateCallback
    - class_path: utils.callbacks.SpectralNormalizationCallback

  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: .
      name: SBM_logs
  profiler: simple
