model:
  # hparams mcmc
  mcmc_steps_tr: 20
  mcmc_learning_rate_tr: 10.0
  mcmc_steps_gen: 100
  mcmc_learning_rate_gen: 5.0
  # hparams optimizer
  alpha_penalty: 0.1
  alpha_ce: 1
  lr: 0.0001
  beta1: 0.0
  sampler:
    class_path: samplers.ImageSampler
    init_args:
      max_len_buffer: 100
  nn_model:
    class_path: nn_models.cnn.MNISTSmallCNN
    init_args:
      conv_hidden_channels_list: [ 16, 32, 64]
      full_hidden_neurons_list: [ 64 ]

data:
  class_path: data_modules.MNISTDataModule
  init_args:
    batch_size: 32
    num_workers: 0
    num_samples: 1000

trainer:
  accelerator: auto
  devices: auto
  max_epochs: 100
  gradient_clip_val: 0.1
  callbacks:
    - class_path: utils.callbacks.BufferSamplerCallback
    - class_path: utils.callbacks.GenerateCallback
      init_args:
        num_steps: 256
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: .
      name: lightning_logs
