model:
  # hparams mcmc
  mcmc_steps: 50
  mcmc_learning_rate: 1.0
  # hparams optimizer
  alpha: 0.1
  lr: 0.0001
  beta1: 0.0
  sampler:
    class_path: samplers.ImageSampler
    init_args:
      max_len_buffer: 10000
  nn_model:
    class_path: nn_models.image.SmallCNN
    init_args:
      hidden_features: 32
      out_dim: 10

data:
  batch_size: 512

trainer:
  accelerator: auto
  devices: auto
  max_epochs: 101
  log_every_n_steps: 50
  gradient_clip_val: 0.1
  callbacks:
    - class_path: utils.callbacks.BufferSamplerCallback
    - class_path: utils.callbacks.GenerateCallback
      init_args:
        num_steps: 256
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: .
      name: experiments
  profiler: simple
