from .MNISTDataModule import MNISTDataModule
from .MNISTSuperpixelDataModule import MNISTSuperpixelDataModule
from .SBMDataModule import SBMDataModule
from .CIFAR10DataModule import CIFAR10DataModule
