img_shape:
- 1
- 28
- 28
batch_size: 128
alpha: 0.1
lr: 0.0001
beta1: 0.0
mcmc_steps: 60
mcmc_learning_rate: 10.0
hidden_features: 32
out_dim: 1
_instantiator: lightning.pytorch.cli.instantiate_module
